### ISSUE TITLE
[Bug]: Link to="//" no longer works

### ISSUE THREAD

**Issue by mariorcosta** [remix-run/react-router#10005]
### What version of React Router are you using?

6.8.0

### Steps to Reproduce

when linking to home using "//" to have the url ending with / no longer works with the newly minor version

### Expected Behavior

redirect to the home page

### Actual Behavior

Uncaught TypeError: Failed to construct 'URL': Invalid URL

**Comment by timdorr** [comment]
#9994 might have an impact here? If not, it could be expanded to cover this case.

**Comment by brophdawg11** [comment]
Hm - either of the implementations is going to detect `//` as a protocol-less URL and treat it as an absolute URL.  @mariorcosta You're saying previously you used `<Link to="//">` to force a trailing slash on your destination URL when linking back to the root route?

**Comment by mariorcosta** [comment]
@brophdawg11 the goal was to ensure that the home URL ended with a '/' such as 'something.com/something/', but this is no longer necessary as it was only a temporary solution to a different issue. 

However, there may still be some people who are impacted by this change.

**Comment by lkwr** [comment]
What about changing the regex in #9994 to something like this:

`/^(?:[a-z][a-z0-9+.-]*:|\/\/)./i`

With an additional dot at the end. This ensure that at least one character is needed after the protocol (in this case the path of the uri).

`https://` will no longer works but `https://a(...)` will do.
Same for `//`, which no longer works but `//b(...)` will do.

Are there protocols or use cases which can have an empty path in the uri? If yes, then this regex would not support it.

**Comment by MadaShindeInai** [comment]
Actually we can see this issue with '//' and '///' if we will try to visit [https://remix.run//](https://remix.run//) or [`https://remix.run///`](https://remix.run///)
In my app i face different behaviour for '//' and '///'.
For '//' (UI shows blank screen) :
In browser:  

<img width="658" alt="Screenshot 2023-01-31 at 20 12 58" src="https://user-images.githubusercontent.com/50995397/215859665-3838e6b6-5328-49f2-a520-98938377beaa.png">  

In VSCode terminal:  

<img width="1009" alt="Screenshot 2023-01-31 at 20 14 06" src="https://user-images.githubusercontent.com/50995397/215859889-0b57573a-0fb2-4856-9a94-0e67cd8fedaa.png">

For '///' (UI shows fallback declared in RouterProvider): 

In browser:  

<img width="655" alt="Screenshot 2023-01-31 at 20 15 17" src="https://user-images.githubusercontent.com/50995397/215860164-436f43ea-e95c-4863-9bf2-2dd797939b7f.png">

**Comment by brophdawg11** [comment]
Hm, we may be getting some wires crossed here.  The `https://remix.run//` issue is a known issue the Remix adapter layers (captured in https://github.com/remix-run/remix/issues/4422, fixed in https://github.com/remix-run/remix/pull/5336).  That fix should go out in the next release.  

I (maybe incorrectly) assumed this was a `react-router-dom` `<Link>` issue since it was opened here.  

If there is a separate `Link` issue please provide a reproduction, otherwise I'll close this out once the linked Remix PR is released 👍

**Comment by MadaShindeInai** [comment]
@brophdawg11 i've updated RR to react-router-dom@6.8.1. Problem with // still exists. AFAIK RR and Remix now is the same. Should i wait for extra fix for RR, or it should be already fixed?

**Comment by MadaShindeInai** [comment]
@brophdawg11 Hello! Any news about that issue?

**Comment by brophdawg11** [comment]
React Router and Remix are _mostly_ the same but not entirely.  Remix has en entire compiler and server-adapter layer on top of React Router.  This thread, based on the examples provided, is referring to a bug that existed in the Remix server-adapter code and was fixed in Remix 1.13.0.  https://reactrouter.com has not been updated to Remix 1.13.0 so it still exhibits the issue.

If there is an issue with `http://{origin}//` in React Router apps, please provide a reproduction and we can dig into it.  At a quick glance it seems to work fine for me using `examples/basic/` on the latest version of `react-router-dom`: 

<img width="411" alt="Screenshot 2023-02-24 at 9 26 01 AM" src="https://user-images.githubusercontent.com/1609022/221204321-e1364802-91db-4623-bb35-d1d27d6f5714.png">
