### ISSUE TITLE
[Bug]: absolute redirect fails while using base url

### ISSUE THREAD

**Issue by amsal** [remix-run/react-router#10052]
### What version of React Router are you using?

6.8.0

### Steps to Reproduce

- Have a react router application hosted in a sub directory e.g. `https://example.com/app1`
- `https://example.com` and `https://example.com/app1` are two independent applications. Served using a reverse proxy

`app1` is the base path and it is set using `basename`

```tsx
const router = createBrowserRouter(
  [
    {
      id: "root",
      path: "/",
      element: (
        <>
          <div>Root</div>
          <Link to="/logout">Logout</Link>
        </>
      ),
    },
    {
      path: "/logout",
      loader: LogoutLoader,
    },
  ],
  {
    basename: "app1",
  }
);
```

```tsx
export const LogoutLoader = async () => {
  return redirect("https://example.com");
};
```

- Go to logout url `https://example.com/app1/logout`

### Expected Behavior

LogoutLoader should redirect user to `https://example.com` as if it was an external redirect to somewhere like `https://google.com`. It should be a redirect via browser instead of react-router.

### Actual Behavior

React router changes the browser URL but the content of the site is still from `https://example.com/app1` instead of `https://example.com`. In the browser dev tools, no request is made to redirect URL. 

Possible bug might be here
https://github.com/remix-run/react-router/blob/6120207a328740a226c462d87be479b7c26b9574/packages/router/router.ts#L3130

**Comment by timdorr** [comment]
This should be fixed by #10033, which is available via 6.8.1-pre.0

**Comment by amsal** [comment]
hi @timdorr 

This doesn't seem to resolve the issue. I have created a minimal repo to reproduce this.

https://github.com/amsal/rr-basename-redirect.git

**Assuming port `5173` is free and used by Vite for this.**

- run `npm run dev`
- go to `localhost:5173/app1`
- click `Logout` link on the page
- redirect is not done as an external redirect

Thanks

**Comment by tomfridental1** [comment]
Any update on this one?

**Comment by tomfridental1** [comment]
Seems the issue is not fixed, baseUrl: '/v2' <Link to="https://sameorigin.com/someroute" /> still considered as internal url

**Comment by tomfridental1** [comment]
That will be great 😎

**Comment by tomfridental1** [comment]
Tested pre.3 looking good, everything works as expected! :)
