### ISSUE TITLE
[Bug]: react-router-dom doesn't expose RemixRouter type so return types fail

### ISSUE THREAD

**Issue by BerkeKaragoz** [remix-run/react-router#10787]
### What version of React Router are you using?

6.15

### Steps to Reproduce

Node v18.12.1
Pnpm v8.4.0
Turbo v1.9.3
Installed packages:
```
      "react": "^18.2.0",
      "react-dom": "^18.2.0",
      "react-router-dom": "^6.15.0"
      Dep:
      "@types/react": "^18.0.25",
      "@types/react-dom": "^18.0.8",
      "@vanilla-extract/css": "^1.12.0",
      "@vanilla-extract/vite-plugin": "^3.8.2",
      "@vitejs/plugin-react": "^4.0.4",
      "interface-cli": "latest",
      "typescript": "^4.8.4",
      "vite": "^4.4.8"
```

Create router:
```ts
import App from "./App"
import { createBrowserRouter } from "react-router-dom"

export const router = createBrowserRouter([{ path: "/", Component: App }])
```

### Expected Behavior

<img width="561" alt="image" src="https://github.com/remix-run/react-router/assets/34271483/b98300eb-e596-4a6c-9b08-bfc1ecb15b6b">

This is the result when we add:
```ts
export type { RemixRouter };
```

To: `react-router-dom@6.15.0_react-dom@18.2.0_react@18.2.0/node_modules/react-router-dom/dist/index.d.ts`

### Actual Behavior

```ts
export const router = createBrowserRouter([{ path: "/", Component: App }])
```

`The inferred type of 'router' cannot be named without a reference to '.pnpm/@remix-run+router@1.8.0/node_modules/@remix-run/router'. This is likely not portable. A type annotation is necessary.ts(2742)`

<img width="741" alt="image" src="https://github.com/remix-run/react-router/assets/34271483/4dec65d7-e597-4edb-a35a-530285b9d2a1">

**Comment by timdorr** [comment]
This type is exported from [`@remix-run/router`](https://github.com/remix-run/react-router/blob/e254133b3f1daa9247d1b39ed46f77a7ffba5cdc/packages/router/router.ts#L57)

**Comment by opswiz** [comment]
having the same. issue. Do We need to install `@remix-run/router` along side `react-router-dom` and import the types from there to make it work with pnpm?

**Comment by rjcnd105** [comment]
> This type is exported from [`@remix-run/router`](https://github.com/remix-run/react-router/blob/e254133b3f1daa9247d1b39ed46f77a7ffba5cdc/packages/router/router.ts#L57)

So how do we solve this?

https://www.npmjs.com/package/@remix-run/router
look at the description of the @remix-run/router package, it says not to use it directly if you only use react-router-dom.

**Comment by 1111mp** [comment]
Why is this issue closed, it still happens with the latest `6.21.3` version.

**Comment by builtbylane** [comment]
Still seeing this issue on vscode.

**Comment by meddyrainzo** [comment]
Is there an update to this? It is still closed but not resolved

**Comment by rogepi** [comment]
```tsx
import { createBrowserRouter, Link } from 'react-router-dom'

export const router: ReturnType<typeof createBrowserRouter> =
  createBrowserRouter([
    {
      path: '/',
      element: (
        <div>
          <h1>Hello World</h1>
          <Link to="about"> About Us </Link>
        </div>
      ),
    },
    {
      path: 'about',
      element: <div>About </div>,
    },
  ])

```

As of today, do we still need to write this to resolve Error Msg?

**Comment by CodeGetters** [comment]
![image](https://github.com/remix-run/react-router/assets/109447998/a0877ebe-29f3-4fce-9a6c-22f1d5ae9db1)
Has the problem not been solved by now?

**Comment by BerkeKaragoz** [comment]
Wow...

If we need to manually install [@remix-run/router](https://github.com/remix-run/react-router/blob/e254133b3f1daa9247d1b39ed46f77a7ffba5cdc/packages/router/router.ts#L57) still, don't make a v6. Why not create a separate package called `remix-router-internals` or something? This just looks like funnelling...

Personally I use a git patch

**Comment by MiloWang2048** [comment]
<img width="529" alt="截屏2024-07-21 21 51 54" src="https://github.com/user-attachments/assets/dd5858ed-8175-4d69-8f82-a40e55a2796a">
 Still getting this error in TS 5.5.2. Can anyone reproduce?

**Comment by ryanbender2** [comment]
> <img alt="截屏2024-07-21 21 51 54" width="529" src="https://private-user-images.githubusercontent.com/19810446/350773009-dd5858ed-8175-4d69-8f82-a40e55a2796a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NzYzMDEsIm5iZiI6MTcyMTc3NjAwMSwicGF0aCI6Ii8xOTgxMDQ0Ni8zNTA3NzMwMDktZGQ1ODU4ZWQtODE3NS00ZDY5LThmODItYTQwZTU1YTI3OTZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDIzMDY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlMTFhYjM0ZmZlMjc3YmVkOTBjOWY2ZTNiZDg3ZjZmNzA4MmJmMDNhNjliY2VmZWVkNDg2YzA1NWEzMzUyMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mW9bQmwlWMFAEDb4v__H8o9RUzGj3APMJg7yNPuNoVI"> Still getting this error in TS 5.5.2. Can anyone reproduce?

Yep, still broken for me on TS 5.5.4.

**Comment by univdev** [comment]
This issue is estimated to be an issue for variables that are extracted from inside the router.tsx file.
Most people who are experiencing this issue are not developing with remix.

Therefore, the answer cited below is the most convenient and practical solution.

> ```tsx
> import { createBrowserRouter, Link } from 'react-router-dom'
> 
> export const router: ReturnType<typeof createBrowserRouter> =
>   createBrowserRouter([
>     {
>       path: '/',
>       element: (
>         <div>
>           <h1>Hello World</h1>
>           <Link to="about"> About Us </Link>
>         </div>
>       ),
>     },
>     {
>       path: 'about',
>       element: <div>About </div>,
>     },
>   ])
> ```

Thank you @rogepi :+1:
