### ISSUE TITLE
[Bug]: RR7 - With `basename` configured, `.data` requests against root index not correctly routed

### ISSUE THREAD

**Issue by mpqmpqm** [remix-run/react-router#12295]
### What version of React Router are you using?

7

### Steps to Reproduce

[Minimal repro](https://github.com/mpqmpqm/rr7-basename)

1. Configure `vite.config.base` and `vite.config.reactRouter.basename`.
2. Add a `Link` component `to` the root index, or an action against the root index.
3. Observe that `.data` requests against root index are routed to `localhost:5173/${basename}.data`, rather than e.g. `localhost:5173/${basename}/_root.data`.
4. Observe that `.data` requests against root index 404.

### Expected Behavior

`.data` requests against root index should resolve accounting for configured `basename`.

### Actual Behavior

`.data` requests against root index 404. `.data` requests against nested routes resolve as expected.

In minimal repro above, try clicking links to `Home` and submitting action on that route. Then try the same at `About`. Observe that `About` works while `Home` (root index) doesn't.

**Comment by mpqmpqm** [comment]
Here are the patches I issued to fix this in my Remix 2.14.0 project: 

```diff
diff --git a/node_modules/@remix-run/react/dist/esm/single-fetch.js b/node_modules/@remix-run/react/dist/esm/single-fetch.js
index 96f10cd..4126369 100644
--- a/node_modules/@remix-run/react/dist/esm/single-fetch.js
+++ b/node_modules/@remix-run/react/dist/esm/single-fetch.js
@@ -300,6 +300,8 @@ function singleFetchUrl(reqUrl) {
   let url = typeof reqUrl === "string" ? new URL(reqUrl, window.location.origin) : reqUrl;
   if (url.pathname === "/") {
     url.pathname = "_root.data";
+  } else if (url.pathname === window.__remixContext.basename) {
+    url.pathname = window.__remixContext.basename.concat("_root.data");
   } else {
     url.pathname = `${url.pathname.replace(/\/$/, "")}.data`;
   }
```

```diff
diff --git a/node_modules/@remix-run/server-runtime/dist/server.js b/node_modules/@remix-run/server-runtime/dist/server.js
index 7e639d9..f2af2db 100644
--- a/node_modules/@remix-run/server-runtime/dist/server.js
+++ b/node_modules/@remix-run/server-runtime/dist/server.js
@@ -128,7 +128,12 @@ const createRequestHandler = (build, mode$1) => {
       }
     } else if (_build.future.v3_singleFetch && url.pathname.endsWith(".data")) {
       let handlerUrl = new URL(request.url);
-      handlerUrl.pathname = handlerUrl.pathname.replace(/\.data$/, "").replace(/^\/_root$/, "/");
+      handlerUrl.pathname = handlerUrl.pathname.replace(/\.data$/, "").replace(
+        _build.basename ?
+          /\/_root$/ :
+          /^\/_root$/,
+        "/"
+      );
       let singleFetchMatches = routeMatching.matchServerRoutes(routes, handlerUrl.pathname, _build.basename);
       response = await handleSingleFetchRequest(serverMode, _build, staticHandler, request, handlerUrl, loadContext, handleError);
       if (_build.entry.module.handleDataRequest) {
```

**Comment by LeoDanielsson** [comment]
We ran into this issue when upgrading our Remix app (without single fetch) to RR7.

We ended up working around it by configuring our reverse proxy to route `/my-app.data` to the app (in addition to `/my-app/*`).

It

**Comment by nikrad7** [comment]
Hello there! We encounter same issue after enable singleFetch future at our roadmap to react-router 7. 

We use cookie based `remix-auth` authorization with cookie `path` option (which equals `/basename`). Since index route is secure and protected by auth middleware, this bug leads to infinite redirect loop between index page and login page. Problem is that browser will not append cookies header for request with `/basename.data` since it doesn't match `path` option, and auth middleware will return singleFetch client redirect to login page route. And for second client request cookies will be sended, since login route match browser cookie `path` logic (`/basename/login`), and result of request will be redirect back to index page.

**Workaroung**
Patch provided by @mpqmpqm is worked, but with slight additional fixes (we at latest, remix 2.15.1 version):
1) basename may be without trailing slash, so we ensure that forward slash will be added before concat basename and `_root.data` patname postfix (at `single-fetch.js`):

```javascript
function singleFetchUrl(reqUrl) {
  let url = typeof reqUrl === "string" ? new URL(reqUrl, window.location.origin) : reqUrl;
  const basename = window.__remixContext.basename;
  if (url.pathname === "/") {
    url.pathname = "_root.data";
  } else if (basename && (url.pathname === basename || url.pathname === `${basename}/`)) {
    url.pathname = basename.endsWith("/") ? basename.concat("_root.data") : basename.concat("/_root.data");
  } else {
    url.pathname = `${url.pathname.replace(/\/$/, "")}.data`;
  }
  return url;
}
```
2) patch both files (`server.js`, `single-fetch.js`) code entries at `dist` and `dist\esm`. At least when using `pnpm` as repo and patch utility.

**Comment by skrhlm** [comment]
could possibly be related to this?
https://github.com/remix-run/react-router/discussions/12536

**Comment by mattoni** [comment]
I'm also running into this issue after migrating a remix app into RR7. I noticed it when using the browser's back button to go back to the entry page, and getting a 404. Also does not happen in dev, but only in a production build.

**Comment by manzaloros** [comment]
I'm also having this issue.

> I noticed it when using the browser's back button to go back to the entry page, and getting a 404. Also does not happen in dev, but only in a production build.

It happens in Remix when the v3_singleFetch is enabled. We have a baseURL defined.

This is a blocker to upgrade from Remix to React Router 7.

Is there any fix for this, other than a patch?

**Comment by manzaloros** [comment]
@ryanflorence , is the team aware of this bug / is there any fix planned?

**Comment by skrhlm** [comment]
My thought here was that the `x.data`-files should be moved inside of it's corresponding path folder, so that each page would be self-contained whatever basename configuration is chosen. 

For example, this structure:
```
about.data
- about/
- - index.html
- - contact/
- - - index.html
- - contact.data
```

would instead be:

```
- about/
- - index.html
- - about.data
- - contact/
- - - index.html
- - - contact.data
```

**Comment by rjaguilar** [comment]
I'm having the same issue with the additional issue that my form action goes to /${basename}.data instead of /${basename}/_root.data causing a 405.

**Comment by Aleuck** [comment]
For React Router v7, I had to create this patch (based on @mpqmpqm's) for it to work consistently in local and production environments.

```diff
diff --git a/node_modules/react-router/dist/development/chunk-SYFQ2XB5.mjs b/node_modules/react-router/dist/development/chunk-SYFQ2XB5.mjs
index 25fce4e..85d529b 100644
--- a/node_modules/react-router/dist/development/chunk-SYFQ2XB5.mjs
+++ b/node_modules/react-router/dist/development/chunk-SYFQ2XB5.mjs
@@ -5811,6 +5811,8 @@ function singleFetchUrl(reqUrl) {
   ) : reqUrl;
   if (url.pathname === "/") {
     url.pathname = "_root.data";
+  } else if (url.pathname === window.__reactRouterContext.basename) {
+    url.pathname = window.__reactRouterContext.basename.concat("_root.data");
   } else {
     url.pathname = `${url.pathname.replace(/\/$/, "")}.data`;
   }
@@ -9009,7 +9011,12 @@ var createRequestHandler = (build, mode) => {
     let response;
     if (url.pathname.endsWith(".data")) {
       let handlerUrl = new URL(request.url);
-      handlerUrl.pathname = handlerUrl.pathname.replace(/\.data$/, "").replace(/^\/_root$/, "/");
+      handlerUrl.pathname = handlerUrl.pathname.replace(/\.data$/, "").replace(
+        _build.basename ?
+          /\/_root$/ :
+          /^\/_root$/,
+        "/"
+      );
       let singleFetchMatches = matchServerRoutes(
         routes,
         handlerUrl.pathname,
diff --git a/node_modules/react-router/dist/development/dom-export.js b/node_modules/react-router/dist/development/dom-export.js
index 59c9a78..af2dbfb 100644
--- a/node_modules/react-router/dist/development/dom-export.js
+++ b/node_modules/react-router/dist/development/dom-export.js
@@ -4471,6 +4471,8 @@ function singleFetchUrl(reqUrl) {
   ) : reqUrl;
   if (url.pathname === "/") {
     url.pathname = "_root.data";
+  } else if (url.pathname === window.__reactRouterContext.basename) {
+    url.pathname = window.__reactRouterContext.basename.concat("_root.data");
   } else {
     url.pathname = `${url.pathname.replace(/\/$/, "")}.data`;
   }
diff --git a/node_modules/react-router/dist/development/index.js b/node_modules/react-router/dist/development/index.js
index 46834a0..42c686c 100644
--- a/node_modules/react-router/dist/development/index.js
+++ b/node_modules/react-router/dist/development/index.js
@@ -5956,6 +5956,8 @@ function singleFetchUrl(reqUrl) {
   ) : reqUrl;
   if (url.pathname === "/") {
     url.pathname = "_root.data";
+  } else if (url.pathname === window.__reactRouterContext.basename) {
+    url.pathname = window.__reactRouterContext.basename.concat("_root.data");
   } else {
     url.pathname = `${url.pathname.replace(/\/$/, "")}.data`;
   }
@@ -9154,7 +9156,12 @@ var createRequestHandler = (build, mode) => {
     let response;
     if (url.pathname.endsWith(".data")) {
       let handlerUrl = new URL(request.url);
-      handlerUrl.pathname = handlerUrl.pathname.replace(/\.data$/, "").replace(/^\/_root$/, "/");
+      handlerUrl.pathname = handlerUrl.pathname.replace(/\.data$/, "").replace(
+        _build.basename ?
+          /\/_root$/ :
+          /^\/_root$/,
+        "/"
+      );
       let singleFetchMatches = matchServerRoutes(
         routes,
         handlerUrl.pathname,
diff --git a/node_modules/react-router/dist/production/chunk-OKQ6KMOJ.mjs b/node_modules/react-router/dist/production/chunk-OKQ6KMOJ.mjs
index 3d1b632..535fe32 100644
--- a/node_modules/react-router/dist/production/chunk-OKQ6KMOJ.mjs
+++ b/node_modules/react-router/dist/production/chunk-OKQ6KMOJ.mjs
@@ -5811,6 +5811,8 @@ function singleFetchUrl(reqUrl) {
   ) : reqUrl;
   if (url.pathname === "/") {
     url.pathname = "_root.data";
+  } else if (url.pathname === window.__reactRouterContext.basename) {
+    url.pathname = window.__reactRouterContext.basename.concat("_root.data");
   } else {
     url.pathname = `${url.pathname.replace(/\/$/, "")}.data`;
   }
@@ -9009,7 +9011,12 @@ var createRequestHandler = (build, mode) => {
     let response;
     if (url.pathname.endsWith(".data")) {
       let handlerUrl = new URL(request.url);
-      handlerUrl.pathname = handlerUrl.pathname.replace(/\.data$/, "").replace(/^\/_root$/, "/");
+      handlerUrl.pathname = handlerUrl.pathname.replace(/\.data$/, "").replace(
+        _build.basename ?
+          /\/_root$/ :
+          /^\/_root$/,
+        "/"
+      );
       let singleFetchMatches = matchServerRoutes(
         routes,
         handlerUrl.pathname,
diff --git a/node_modules/react-router/dist/production/dom-export.js b/node_modules/react-router/dist/production/dom-export.js
index 8d83202..cac7673 100644
--- a/node_modules/react-router/dist/production/dom-export.js
+++ b/node_modules/react-router/dist/production/dom-export.js
@@ -4471,6 +4471,8 @@ function singleFetchUrl(reqUrl) {
   ) : reqUrl;
   if (url.pathname === "/") {
     url.pathname = "_root.data";
+  } else if (url.pathname === window.__reactRouterContext.basename) {
+    url.pathname = window.__reactRouterContext.basename.concat("_root.data");
   } else {
     url.pathname = `${url.pathname.replace(/\/$/, "")}.data`;
   }
diff --git a/node_modules/react-router/dist/production/index.js b/node_modules/react-router/dist/production/index.js
index d5cace8..1f1138a 100644
--- a/node_modules/react-router/dist/production/index.js
+++ b/node_modules/react-router/dist/production/index.js
@@ -5956,6 +5956,8 @@ function singleFetchUrl(reqUrl) {
   ) : reqUrl;
   if (url.pathname === "/") {
     url.pathname = "_root.data";
+  } else if (url.pathname === window.__reactRouterContext.basename) {
+    url.pathname = window.__reactRouterContext.basename.concat("_root.data");
   } else {
     url.pathname = `${url.pathname.replace(/\/$/, "")}.data`;
   }
@@ -9154,7 +9156,12 @@ var createRequestHandler = (build, mode) => {
     let response;
     if (url.pathname.endsWith(".data")) {
       let handlerUrl = new URL(request.url);
-      handlerUrl.pathname = handlerUrl.pathname.replace(/\.data$/, "").replace(/^\/_root$/, "/");
+      handlerUrl.pathname = handlerUrl.pathname.replace(/\.data$/, "").replace(
+        _build.basename ?
+          /\/_root$/ :
+          /^\/_root$/,
+        "/"
+      );
       let singleFetchMatches = matchServerRoutes(
         routes,
         handlerUrl.pathname,

```

**Comment by cmatlock-comp** [comment]
> For React Router v7, I had to create this patch (based on [@mpqmpqm](https://github.com/mpqmpqm)'s) for it to work consistently in local and production environments.
> 
> diff --git a/node_modules/react-router/dist/development/chunk-SYFQ2XB5.mjs b/node_modules/react-router/dist/development/chunk-SYFQ2XB5.mjs
> index 25fce4e..85d529b 100644
> --- a/node_modules/react-router/dist/development/chunk-SYFQ2XB5.mjs
> +++ b/node_modules/react-router/dist/development/chunk-SYFQ2XB5.mjs
> @@ -5811,6 +5811,8 @@ function singleFetchUrl(reqUrl) {
>    ) : reqUrl;
>    if (url.pathname === "/") {
>      url.pathname = "_root.data";
> +  } else if (url.pathname === window.__reactRouterContext.basename) {
> +    url.pathname = window.__reactRouterContext.basename.concat("_root.data");
>    } else {
>      url.pathname = `${url.pathname.replace(/\/$/, "")}.data`;
>    }
> @@ -9009,7 +9011,12 @@ var createRequestHandler = (build, mode) => {
>      let response;
>      if (url.pathname.endsWith(".data")) {
>        let handlerUrl = new URL(request.url);
> -      handlerUrl.pathname = handlerUrl.pathname.replace(/\.data$/, "").replace(/^\/_root$/, "/");
> +      handlerUrl.pathname = handlerUrl.pathname.replace(/\.data$/, "").replace(
> +        _build.basename ?
> +          /\/_root$/ :
> +          /^\/_root$/,
> +        "/"
> +      );
>        let singleFetchMatches = matchServerRoutes(
>          routes,
>          handlerUrl.pathname,
> diff --git a/node_modules/react-router/dist/development/dom-export.js b/node_modules/react-router/dist/development/dom-export.js
> index 59c9a78..af2dbfb 100644
> --- a/node_modules/react-router/dist/development/dom-export.js
> +++ b/node_modules/react-router/dist/development/dom-export.js
> @@ -4471,6 +4471,8 @@ function singleFetchUrl(reqUrl) {
>    ) : reqUrl;
>    if (url.pathname === "/") {
>      url.pathname = "_root.data";
> +  } else if (url.pathname === window.__reactRouterContext.basename) {
> +    url.pathname = window.__reactRouterContext.basename.concat("_root.data");
>    } else {
>      url.pathname = `${url.pathname.replace(/\/$/, "")}.data`;
>    }
> diff --git a/node_modules/react-router/dist/development/index.js b/node_modules/react-router/dist/development/index.js
> index 46834a0..42c686c 100644
> --- a/node_modules/react-router/dist/development/index.js
> +++ b/node_modules/react-router/dist/development/index.js
> @@ -5956,6 +5956,8 @@ function singleFetchUrl(reqUrl) {
>    ) : reqUrl;
>    if (url.pathname === "/") {
>      url.pathname = "_root.data";
> +  } else if (url.pathname === window.__reactRouterContext.basename) {
> +    url.pathname = window.__reactRouterContext.basename.concat("_root.data");
>    } else {
>      url.pathname = `${url.pathname.replace(/\/$/, "")}.data`;
>    }
> @@ -9154,7 +9156,12 @@ var createRequestHandler = (build, mode) => {
>      let response;
>      if (url.pathname.endsWith(".data")) {
>        let handlerUrl = new URL(request.url);
> -      handlerUrl.pathname = handlerUrl.pathname.replace(/\.data$/, "").replace(/^\/_root$/, "/");
> +      handlerUrl.pathname = handlerUrl.pathname.replace(/\.data$/, "").replace(
> +        _build.basename ?
> +          /\/_root$/ :
> +          /^\/_root$/,
> +        "/"
> +      );
>        let singleFetchMatches = matchServerRoutes(
>          routes,
>          handlerUrl.pathname,
> diff --git a/node_modules/react-router/dist/production/chunk-OKQ6KMOJ.mjs b/node_modules/react-router/dist/production/chunk-OKQ6KMOJ.mjs
> index 3d1b632..535fe32 100644
> --- a/node_modules/react-router/dist/production/chunk-OKQ6KMOJ.mjs
> +++ b/node_modules/react-router/dist/production/chunk-OKQ6KMOJ.mjs
> @@ -5811,6 +5811,8 @@ function singleFetchUrl(reqUrl) {
>    ) : reqUrl;
>    if (url.pathname === "/") {
>      url.pathname = "_root.data";
> +  } else if (url.pathname === window.__reactRouterContext.basename) {
> +    url.pathname = window.__reactRouterContext.basename.concat("_root.data");
>    } else {
>      url.pathname = `${url.pathname.replace(/\/$/, "")}.data`;
>    }
> @@ -9009,7 +9011,12 @@ var createRequestHandler = (build, mode) => {
>      let response;
>      if (url.pathname.endsWith(".data")) {
>        let handlerUrl = new URL(request.url);
> -      handlerUrl.pathname = handlerUrl.pathname.replace(/\.data$/, "").replace(/^\/_root$/, "/");
> +      handlerUrl.pathname = handlerUrl.pathname.replace(/\.data$/, "").replace(
> +        _build.basename ?
> +          /\/_root$/ :
> +          /^\/_root$/,
> +        "/"
> +      );
>        let singleFetchMatches = matchServerRoutes(
>          routes,
>          handlerUrl.pathname,
> diff --git a/node_modules/react-router/dist/production/dom-export.js b/node_modules/react-router/dist/production/dom-export.js
> index 8d83202..cac7673 100644
> --- a/node_modules/react-router/dist/production/dom-export.js
> +++ b/node_modules/react-router/dist/production/dom-export.js
> @@ -4471,6 +4471,8 @@ function singleFetchUrl(reqUrl) {
>    ) : reqUrl;
>    if (url.pathname === "/") {
>      url.pathname = "_root.data";
> +  } else if (url.pathname === window.__reactRouterContext.basename) {
> +    url.pathname = window.__reactRouterContext.basename.concat("_root.data");
>    } else {
>      url.pathname = `${url.pathname.replace(/\/$/, "")}.data`;
>    }
> diff --git a/node_modules/react-router/dist/production/index.js b/node_modules/react-router/dist/production/index.js
> index d5cace8..1f1138a 100644
> --- a/node_modules/react-router/dist/production/index.js
> +++ b/node_modules/react-router/dist/production/index.js
> @@ -5956,6 +5956,8 @@ function singleFetchUrl(reqUrl) {
>    ) : reqUrl;
>    if (url.pathname === "/") {
>      url.pathname = "_root.data";
> +  } else if (url.pathname === window.__reactRouterContext.basename) {
> +    url.pathname = window.__reactRouterContext.basename.concat("_root.data");
>    } else {
>      url.pathname = `${url.pathname.replace(/\/$/, "")}.data`;
>    }
> @@ -9154,7 +9156,12 @@ var createRequestHandler = (build, mode) => {
>      let response;
>      if (url.pathname.endsWith(".data")) {
>        let handlerUrl = new URL(request.url);
> -      handlerUrl.pathname = handlerUrl.pathname.replace(/\.data$/, "").replace(/^\/_root$/, "/");
> +      handlerUrl.pathname = handlerUrl.pathname.replace(/\.data$/, "").replace(
> +        _build.basename ?
> +          /\/_root$/ :
> +          /^\/_root$/,
> +        "/"
> +      );
>        let singleFetchMatches = matchServerRoutes(
>          routes,
>          handlerUrl.pathname,

Can verify this works, used patch-package https://www.npmjs.com/package/patch-package. Thank You!!! @Aleuck

**Comment by brophdawg11** [comment]
This should be resolved by #12898 and will be included in the next release

**Comment by manzaloros** [comment]
@brophdawg11 , thanks for the update.

On 7.2.0 I'm still getting the 404 error when following a link to the root route. I have a basename configured in the `react-router.config.ts`.

**Comment by s-cochrane** [comment]
@manzaloros, from what I can tell this didn't make the 7.2 cut. This was merged into dev right after 7.2 was cut for a release. I have my eye on this one as well, but I think we'll be waiting for 7.3.

**Comment by manzaloros** [comment]
@s-cochrane , thanks! After upgrading to 7.3.0 it looks like the issue is fixed!

Just curious: I made a quick RR7 app from scratch before 7.3.0 and didn't notice this issue occurring. Why did it occur only on my app that I upgraded from Remix?

**Comment by s-cochrane** [comment]
@manzaloros - I'm not sure about the specifics of your setup, but we observed the issues when we put RR behind a reverse-proxy. In our case we're replacing a legacy application with a new RR app, and we can't move the legacy app off of the base URL. Because the RR app was being routed to via the reverse proxy it made the break very obvious for us.  The app would work if we opened the app directly, but as soon as we put it behind the reverse proxy the issues would surface. Instead of routing static assets and data requests on top of the `basename` path, it would incorrectly add those paths to the `basename`. [This](https://github.com/remix-run/react-router/issues/12295#issuecomment-2617140598) link above explains the issue we were seeing exactly.
