### ISSUE TITLE
[bug] React Router v7 completely broke remix-hook-form

### ISSUE THREAD

**Issue by AlemTuzlak** [remix-run/react-router#12401]
### I'm using React Router as a...

framework

### Reproduction

https://stackblitz.com/edit/github-k5nghg?file=app%2Froutes%2Fhome.tsx

### System Info

```shell
Doesn't matter, repro above!
```

### Used Package Manager

npm

### Expected Behavior

It works

### Actual Behavior

it dies.
After my investigation I figured out that it dies in `entry.server.ts` and if I wrap it into a `ClientOnly` component then it works. All I did to upgrade `remix-hook-form` to support react-router v7 is change the `peerDependency` from `@remix-run/react` to `react-router` and this used to work just fine before. I am not sure if something changed internally but I'd expect this to work, the source code that runs is here:
https://github.com/forge42dev/remix-hook-form/blob/main/src/hook/index.tsx
You can see everything I use from react-router there. Thank you for the help!

**Comment by brookslybrand** [comment]
Looks like the same issue as #12399, we're getting a patch out shortly

Thanks for your patience @AlemTuzlak!

**Comment by AlemTuzlak** [comment]
Thank you Brooks 🫶

**Comment by brookslybrand** [comment]
Fixed by #12437  and available in v7.0.2

Thanks for your patience Alem! I'm going to go ahead and close this issue

**Comment by atarbalouti** [comment]
@brookslybrand @AlemTuzlak I figured out, this is only fixed until node v22, in node v23 it is still causing the same issue :)

**Comment by hauptrolle** [comment]
@brookslybrand It is still broken for me even on on `node v22.12.0` and `react-router v.7.0.2`.  Using the the same code as @AlemTuzlak in his reproduction.

**Comment by brookslybrand** [comment]
Re-opened in #12475

**Comment by cemalokten** [comment]
I'm also experiencing this issue, all versions of node, react-router v.7.0.2.
