### ISSUE TITLE
createRoutesStub fails type checking

### ISSUE THREAD

**Issue by silvenon** [remix-run/react-router#12494]
### I'm using React Router as a...

framework

### Reproduction

Create a route `app/routes/home.tsx` route with the following content:

```tsx
import type { Route } from './+types/home'

export function loader(_: Route.LoaderArgs) {
  return { message: 'Hello world!' }
}

export default function Home({ loaderData }: Route.ComponentProps) {
  return <h1>{loaderData.message}</h1>
}
```

Register the route in `app/routes.ts`:

```ts
import { type RouteConfig, route } from '@react-router/dev/routes'

export default [
  route('/', './routes/home.tsx'),
]
```

Now create a `app/routes/home.test.tsx` file to test this route:

```tsx
import { createRoutesStub } from 'react-router'
import { render, screen } from '@testing-library/react'
import * as homeRoute from './home'

const HomeStub = createRoutesStub([
  {
    index: true,
    loader: homeRoute.loader,
    Component: homeRoute.default,
  },
])

test('home', () => {
  render(<HomeStub />)
  screen.getByText('Hello world!')
})
```

### System Info

```shell
System:
    OS: macOS 15.1.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 113.45 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.18.1 - ~/.n/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.8.2 - ~/.n/bin/npm
    pnpm: 9.14.4 - /opt/homebrew/bin/pnpm
    bun: 1.1.29 - ~/.bun/bin/bun
  Browsers:
    Chrome: 131.0.6778.109
    Edge: 131.0.2903.86
    Safari: 18.1.1
  npmPackages:
    @react-router/dev: ^7.0.2 => 7.0.2
    @react-router/node: ^7.0.2 => 7.0.2
    @react-router/serve: ^7.0.2 => 7.0.2
    react-router: ^7.0.2 => 7.0.2
    vite: ^6.0.3 => 6.0.3
```

### Used Package Manager

npm

### Expected Behavior

Both the test and type checking passes.

### Actual Behavior

The test passes, but type checking unfortunately doesn't because `createRoutesStub` expects each route segment to have the predefined stub shapes, so if any data loading is going on this will cause those segments to not match those shapes anymore. For example:

```
typescript: Type '({ loaderData }: ComponentProps) => Element' is not assignable to type 'ComponentType<{}> | null | undefined'.
  Type '({ loaderData }: ComponentProps) => Element' is not assignable to type 'FunctionComponent<{}>'.
    Types of parameters '__0' and 'props' are incompatible.
      Type '{}' is missing the following properties from type 'ComponentProps': params, loaderData, matches
```

**Comment by Geb-algebra** [comment]
I encountered the same issue too. Because of this I continue using `LoaderFunctionArgs` and `useLoaderData`, even though I'm really excited about using generated types 😢

**Comment by silvenon** [comment]
I supresss all the type errors in my tests via ts-expect-error, even though there are a lot of them. No reason not to take advantage of generated types right now 😉

**Comment by silvenon** [comment]
The testing utilities are completely out of sync with the new route API, this isn't only a TypeScript problem. For example, if I pass in a `loader` its data won't be passed as `loaderData` to `Component`, I have to wrap the compoennt it in order for it to work:

```tsx
loader: homeRoute.loader,
Component: () => {
  const loaderData = useLoaderData<typeof homeRoute.loader>()
  const Home = homeRoute.default
  return <Home loaderData={loaderData} />
}
```

It took me a while to figure out, I just assumed they were updated as well.

**Comment by MattyBalaam** [comment]
This sadly seems to be an unloved part of the switch, does nobody test?

Our workaround for now:

```
import * as React from 'react';
import {
  createRoutesStub,
  Outlet,
  useActionData,
  useLoaderData,
} from 'react-router';

type Routes = Parameters<typeof createRoutesStub>[0];

type StubRouteObject = Routes[number];

const patchRoute = (route: StubRouteObject) => {
  const { action, children, Component } = route;

  if (children) {
    // recursively patch children
    route.children = children.map(patchRoute);
  }

  if (Component) {
    // Temp workaround until createRoutesStub has native support for routeData
    // https://github.com/remix-run/react-router/issues/12494

    route.Component = (props: Record<string, unknown>) => {
      // eslint-disable-next-line react-hooks/rules-of-hooks
      const loaderData = useLoaderData();
      // eslint-disable-next-line react-hooks/rules-of-hooks
      const actionData = useActionData();

      const allProps = {
        ...props,
        loaderData,
        actionData,
      } as React.ComponentProps<typeof Component>;

      return <Component {...allProps} />;
    };
  }
  return route;
};

export const createStub = (routes: Routes, context?: Context) => {
  return createRoutesStub(
    [
      {
        id: "root",
        Component: Outlet,
        children: routes.map(patchRoute),
      },
    ],
    context,
  );
};
```

**Comment by silvenon** [comment]
It has the basic stuff that you most often would need, but you might sometimes want to use matches, params… those are missing from the patch. And I think I'd like my solution to use the existing `routes.ts` file, that way I could attempt to use real paths and parent/layout routes etc.

But the fact that this incompatibility is still unaddressed by the team worries me, to the extent that I'm wondering whether they simply forgot about the testing API. To me `createRoutesStub` was the symbol that this framework cares about unit testing, while Next.js doesn't have a unit testing story at all.

But maybe with the introduction of Browser Mode in Vitest we should strive towards testing our routes in browsers, where we can see the client data as well, I haven't haven't tried how that would work yet. Lack of client data is the shortcoming of unit testing with `createRoutesStub` with DOM emulation.

**Comment by MattyBalaam** [comment]
Yes, to be clear this is just a very basic patch.

Browser Mode in vitest will still need you to use this testing harness, in fact we run our component tests in a browser inside Playwright directly at the moment.

**Comment by silvenon** [comment]
I have yet to figure that out. Thanks for the pointers.

**Comment by gothedistance** [comment]
When a route definition includes path parameters, the { loader, action } provided to createRoutesStub causes a type error: it expects Routes.LoaderArgs / Routes.ActionArgs, but the definitions end up matching LoaderFunctionArgs and ActionFunctionArgs. The type error doesn't prevent it from working, but still occurs.

```ts:route.ts
export default [
  route("login", "routes/login.tsx"),
  route("/detail/:itemId", "routes/detail/index.tsx"),
] satisfies RouteConfig;
```

```ts
import LoginComponent, { action } from "./login";
  // action can resolve Route.ActionArgs
  const Stub = createRoutesStub([
    {
      path: "/login",
      Component: LoginComponent,
      action: action
    },
  ]);
```

```ts
  const Stub = createRoutesStub([
    {
      path: "/detail/:itemId",
      // type error 
      loader: loader,
      Component: DetailComponent,
    },
  ],);
```

error is, `Type 'LoaderFunctionArgs<any>' is not assignable to type 'LoaderArgs'.`

Change to LoaderFunctionArgs solve this error, dispite lose generic types 😅 

```
Type '({ context, params }: LoaderArgs) => Promise<{ item: ItemSearchRow; }>' is not assignable to type 'LoaderFunction'.
  Type '({ context, params }: LoaderArgs) => Promise<{ item: ItemSearchRow;  }>' is not assignable to type '(args: LoaderFunctionArgs<any>, handlerCtx?: unknown) => unknown'.
    Types of parameters '__0' and 'args' are incompatible.
      Type 'LoaderFunctionArgs<any>' is not assignable to type 'LoaderArgs'.
        Types of property 'params' are incompatible.
          Type 'Params<string>' is not assignable to type '{ itemId: string; } & { [key: string]: string | undefined; }'.
            Property '"itemId"' is missing in type 'Params<string>' but required in type '{ itemId: string; }'.
```

**Comment by silvenon** [comment]
Seems like this is fixed in #13528, right @brophdawg11?

**Comment by silvenon** [comment]
Yup, confirmed, my tests are passing.

**Comment by egorpavlikhin** [comment]
This is still an issue in version `7.6.0`. Here is the simplest reproduction using the example from official docs:

```typescript
import {Form, useActionData} from 'react-router';

export type LoginformProps = {
  props1?: string;
};

export const LoginForm = ({ props1 }: LoginformProps) => {
  const {errors} = useActionData();
  return (
    <Form method="post">
      <label>
        <input type="text" name="username" />
        {errors?.username && <div>{errors.username}</div>}
      </label>

      <label>
        <input type="password" name="password" />
        {errors?.password && <div>{errors.password}</div>}
      </label>

      <button type="submit">Login</button>
    </Form>
  );
};
```

```typescript
import {createRoutesStub} from 'react-router';
import {render, screen, waitFor} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {LoginForm} from './test.js';

test("LoginForm renders error messages", async () => {
  const USER_MESSAGE = "Username is required";
  const PASSWORD_MESSAGE = "Password is required";

  const Stub = createRoutesStub([
    {
      path: "/login",
      Component: LoginForm,
      action() {
        return {
          errors: {
            username: USER_MESSAGE,
            password: PASSWORD_MESSAGE,
          },
        };
      },
    },
  ]);

  // render the app stub at "/login"
  render(<Stub initialEntries={["/login"]} />);

  // simulate interactions
  userEvent.click(screen.getByText("Login"));
  await waitFor(() => screen.findByText(USER_MESSAGE));
  await waitFor(() => screen.findByText(PASSWORD_MESSAGE));
});
```

```
Types of parameters __0 and props are incompatible.
Type
{   params: Readonly<Partial<string | Record<string, string | undefined>>>;   loaderData: unknown;   actionData: unknown;   matches: UIMatch<unknown, unknown>[]; }
has no properties in common with type LoginformProps
```

**Comment by silvenon** [comment]
Your `LoginFormProps` are incorrect, your component will receive `actionData` (and other props). That's what your TypeScript error is about. If you use React Router as a framework you can automatically [generate types for your routes](https://reactrouter.com/how-to/route-module-type-safety).

Depends on your use case how you get around this.

Unrelated: you don't need `waitFor` in your test examples, `screen.findBy` queries already wait until these are available (as long as you `await` them).

**Comment by MattyBalaam** [comment]
Sounds to me like the documentation needs updating?

**Comment by titenis** [comment]
Typechecking problem still persists. `createRoutesStub` routes object has hardcoded loader/action types `loader?: LoaderFunction | boolean;` meaning that if you try in a test to wire a loader that uses generated types `async ({ request }: Route.ClientLoaderArgs)`, typechecking starts screaming
```
TS2322: Type
({request}: Route.ClientLoaderArgs) => Promise<{
    .......
}>
is not assignable to type LoaderFunction
```

Current hacky solution is to cast that loader to LoaderFunction inside test
```
{
        path: '/my_path/,
        loader: clientLoader as LoaderFunction,
      }
```

**Comment by silvenon** [comment]
I believe this helper isn't for testing client data, IIRC it says as much in the code comments, and recommends E2E instead for testing that flow.

**Comment by silvenon** [comment]
Just to add to my comment above.

https://github.com/remix-run/react-router/blob/11e1db89e36299c0b2dec94819b544d10a7169c9/packages/react-router/lib/dom/ssr/routes-test-stub.tsx#L224-L226

**Comment by rub1e** [comment]
Documentation in comments in the framework code 🙃
