### ISSUE TITLE
Fetcher sometimes transitions  to idle before new loader data is available

### ISSUE THREAD

**Issue by updbqn** [remix-run/react-router#14506]
### Reproduction

MRE: https://stackblitz.com/edit/github-dbzca6qx?file=app%2Froutes%2Fhome.tsx

I'm attempting to do an optimistic update of a toggle following the pattern in the docs. Something like:

```typescript
  const status =
    (fetcher.formData && fetcher.formData.get('status') === 'true') ??
    item.status;
```

Sometimes I get a flicker of stale data during the update e.g.

1. false (initial)
2. true (optimistic)
3. false (fetcher data no longer available, old loader data shown?)
4. true (new loader data comes in)

Try clicking the items in the stackblitz. Here is a short video of the behavior as well.

https://github.com/user-attachments/assets/92a26618-5fde-4faa-915b-8fdb01a5ff7e

When logging fetcher state/formdata/loadeData I see the following transition on "flickering" updates:

<img width="623" height="456" alt="Image" src="https://github.com/user-attachments/assets/24893cdd-852f-412b-bf7a-05da7d8e84f8" />

i.e. it looks like fetcher.formData is undefined before the new loaderData is available.

The problem seems to go away if I make the loader slower. Though I haven't fully verified that yet.

I couldn't find anything about this in the documentation. Is this expected behavior or am I doing anything wrong?

### System Info

```shell
-
```

### Used Package Manager

npm

### Expected Behavior

New loaderData is always available before fetcher becomes idle.

### Actual Behavior

There is a race condition where fetcher.formData is undefined before new loaderData is available.

**Comment by SarthakRawat-1** [comment]
@brophdawg11 
Hello, I think I can work on fixing this. The issue seems to be in handleFetcherAction and getDoneFetcher.
getDoneFetcher is clearing data fields when transitioning to idle state but for revalidation, the the formData should be preserved until the revalidation completes.

**Comment by brophdawg11** [comment]
Thanks!  I haven't had a chance to look into it but if you want to push up a PR and tag me I'll take a look 👍

**Comment by SarthakRawat-1** [comment]
Hello @brophdawg11 
Sorry it took so much time but I have fixed it here :- #14612

**Comment by brophdawg11** [comment]
I'm not able to reproduce the issue in the stackblitz - do we know a way to reliably reproduce?

**Comment by updbqn** [comment]
I can still reproduce this reliably in StackBlitz. It happens at least 1 in 10 clicks.
Since it looks like some type of race condition I guess it might depend on e.g. hardware.
Let me know what else I can do to help with troubleshooting.

**Comment by brophdawg11** [comment]
Can you find a way to make it happen more repeatably?  We need to be able to nail down what's happening, and more importantly find a repeatable failing test to use to validate a fix.  If speed is a factor - what combo triggers it?  Slow loader/slow action?  Slow loader/fast action?  Etc.  What about click speed on subsequent items?

**Comment by updbqn** [comment]
I think it's going to be pretty hard to find a set of parameters that works for all hardware.

From manual testing slowing down the loader in my production application seemed to help reduce user visible flicker. Though maybe that is only on my hardware?

In the synthetic example it doesn't seem to happen at all without artificial slow down of rendering.

Looking at it from another perspective.

Can we agree that the following sequence of states should be impossible:

User clicks to toggle: false → true

1. hasSubmitted = true, fetcher.formData.value = true, expectedValue = true
   └─► UI shows: true ✓ (optimistic)
2. fetcher.formData = undefined, loaderData.value = false (stale)
   └─► UI shows: false ✗ (FLICKER)
3. loaderData.value = true, hasSubmitted = false
   └─► UI shows: true ✓

Without knowing much about the internal of react / react-router that should be possible and desirable to prevent?

If you want evidence of that this happens at all you should be able to programmatically detect it with something like:

```js
// Note that this doesn't always mean there was a user visible flicker (time in invalid state was too short). It will probably also miss some flickers due to blocking in other parts.
const isFlicker = 
  hasSubmitted &&                            // Set to true on submit, set to flase once loader data matches expected
  fetcher.formData === undefined &&          // No optimistic data
  loaderData.value !== expectedValue;        // Loader data doesn't match expected
```

Then submit the form data on an interval with fetcher.submit. Potentially try increasing the render delay by 1ms every click.

**Comment by timdorr** [comment]
I created a repro (-ish) here: https://stackblitz.com/edit/github-dbzca6qx-cdq8lgoy?file=app%2Froutes%2Fhome.tsx

I increased the render time a bit by doing more loops on the sqrt. I also added a ref to track the intended state vs the state from the fetcher. I limited it to Item 5 to avoid noise in the logs. So, click that one a bunch of times and it will eventually trigger a debugger (if you have Dev Tools open).
