### ISSUE TITLE
[Bug]: `createMemoryRouter` breaks programmatic routing in tests

### ISSUE THREAD

**Issue by barclayd** [remix-run/react-router#9400]
### What version of React Router are you using?

`6.4.1`

### Jest version

`29.0.2`

### Steps to Reproduce

```javascript
// router.js

import {
  createBrowserRouter,
  createRoutesFromElements,
  Link,
  Outlet,
  Route,
} from 'react-router-dom';

export const Nav = () => (
  <nav>
    <Link to="/">Home</Link>
    <Link to="dashboard">Dashboard</Link>
  </nav>
);

export const Home = () => (
  <>
    <Nav />
    <h2>Home</h2>
    <Outlet />
  </>
);

export const Dashboard = () => <h2>Dashboard</h2>;

export const createRoutes = () =>
  createRoutesFromElements(
    <Route path="/" element={<Home />}>
      <Route path="dashboard" element={<Dashboard />} />
    </Route>,
  );

export const createRouter = () => createBrowserRouter(createRoutes());
```

```javascript
// index.js

import * as ReactDOM from 'react-dom/client';
import { RouterProvider } from 'react-router-dom';
import { createRouter } from './router';

const container = document.getElementById('root');

if (!container) {
  throw new Error(
    'Missing container - unable to createRoot to elementWithId=root',
  );
}

const root = ReactDOM.createRoot(container);

const router = createRouter();

root.render(<RouterProvider router={router} />);
```

### Failing test when rendered using `createMemoryRouter` and `<RouterProvider />`
```javascript
// index.createMemoryRouter.test.js (failing)

import { fireEvent, render, screen } from '@testing-library/react';
import { createMemoryRouter, RouterProvider } from 'react-router-dom';
import { createRoutes } from './router';

const renderWithRouter = (route = '/') => {
  const router = createMemoryRouter(createRoutes(), {
    initialEntries: [route],
  });
  return render(<RouterProvider router={router} />);
};

it('can render multiple routes', () => {
  renderWithRouter({ route: '/' });

  expect(screen.getByRole('heading', { name: 'Home' })).toBeVisible();

  fireEvent.click(screen.getByRole('link', { name: 'Dashboard' }));

  expect(screen.getByRole('heading', { name: 'Dashboard' })).toBeVisible();
});
```

### Passing test when rendered using `<MemoryRouter />`
```javascript
// index.memoryRouter.test.js (passing)

import { fireEvent, render, screen } from '@testing-library/react';
import { MemoryRouter, Routes, Route } from 'react-router-dom';
import { Home } from '../src/components/Home';
import { Dashboard } from '../src/components/Dashboard';

const renderWithRouter = (route = '/') => {
  return render(
    <MemoryRouter initialEntries={[route]}>
      <Routes>
        <Route path="/" element={<Home />}>
          <Route path="dashboard" element={<Dashboard />} />
        </Route>
      </Routes>
    </MemoryRouter>,
  );
};

it('can render multiple routes', () => {
  renderWithRouter({ route: '/' });

  expect(screen.getByRole('heading', { name: 'Home' })).toBeVisible();

  fireEvent.click(screen.getByRole('link', { name: 'Dashboard' }));

  expect(screen.getByRole('heading', { name: 'Dashboard' })).toBeVisible();
});

```

### Expected Behavior

`index.createMemoryRouter.test.js` should pass

### Actual Behavior

Using `createMemoryRouter` breaks previously passing tests where the router would dynamically load routes navigated programmatically during the tests.

The router when created with `createMemoryRouter` will no longer re-render after navigating to a new route programatically during the tests, thus breaking the example test case provided. 

As a result, the `screen.debug()` provided by `@testing-library/react` shows `<h2>Home</h2>`. This indicates that the `createMemoryRouter` has not done its job in dynamically routing and rendering to the `/dashboard` route as it should be displaying `<h2>Dashboard</h2>` when routed and re-rendered successfully.

### Test output

<p align="center">
<img width="75%" alt="failing_test_output_1" src="https://user-images.githubusercontent.com/39765499/193910942-78f3845f-ceaf-4b0b-961e-e2478baf79f3.png">
<img width="75%" alt="failing_test_output_2" src="https://user-images.githubusercontent.com/39765499/193911077-97ffa868-9bf7-46fd-8935-5982256c659f.png">
</p>

**Comment by timdorr** [comment]
@brophdawg11 Is this related to #9265?

**Comment by timdorr** [comment]
Dammit, I love to hit that close button...

**Comment by brophdawg11** [comment]
👋 @barclayd - I'm inclined to believe this is something going on in your local setup as our internal test suites do this type of navigation via `jest` without issues.  I also put together a small reproduction using your code above and everything passes there as well: https://github.com/brophdawg11/react-router-memory-router-jest-reproduction.

I'm going to close this out for now, but if you can provide a minimal reproduction of the issue please feel free to re-open!

**Comment by kirim-Lee** [comment]
I had same bug while using RouterProvider.
I saw upper example and realized that the issue is solved after use 'jest-fetch-mock' lib.
but this still seems to be an issue. cause it's hard to think of using fetch while using router.

**Comment by visoft** [comment]
@brophdawg11 - I took the reproduction of the code that you provided, unfortunately the `createMemoryRouter` test still doesn't pass. It doesn't navigate when clicking a Link on the page. The MemoryRouter test passes but I need a data router because I'm using useBlocker in my component.

**Comment by brophdawg11** [comment]
Can you provide a reproduction as requested above?

**Comment by visoft** [comment]
I ended up fixing the problem, it was the node version I was using; Node 18.15.0. The problem was solved by upgrading node. And the issue exists here: https://github.com/remix-run/react-router/issues/10273

**Comment by barclayd** [comment]
If you can't upgrade your version of Node, use the following polyfill:

```bash
npm i -D node-fetch
```

```tsx
import nodeFetch, { Request, Response } from 'node-fetch';

// fix for undici bug in Node < 18.6.0 https://github.com/nodejs/undici/pull/1910#issuecomment-1464495619
// remove this line when after upgrading to Node 18.6.0 or higher
Object.assign(global, { fetch: nodeFetch, Request, Response });
